name: more-limesurvey

services:
  limesurvey:
    image: .
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -sfI -m5 http://localhost:8080 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_USER: ${ADMIN_USER}
      # Initial Password, will be changed on setup
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  database:
    image: postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 1s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
