Alias /css    /var/www/html/vendor/kcfinder/css
Alias /js     /var/www/html/vendor/kcfinder/js
Alias /themes /var/www/html/vendor/kcfinder/themes

RewriteEngine On
RewriteRule ^/browse\.php$      /vendor/kcfinder/browse.php      [L,PT]
RewriteRule ^/upload\.php$      /vendor/kcfinder/upload.php      [L,PT]
RewriteRule ^/js_localize\.php$ /vendor/kcfinder/js_localize.php [L,PT]
RewriteRule ^/css\.php$         /vendor/kcfinder/css.php         [L,PT]

<Directory /var/www/html/vendor/kcfinder>
    Options -Indexes
    AllowOverride All
    Require all granted
</Directory>